# docker-compose-replicas-bad.yml

services:
  postgres_workshop:
    image: postgres:15
    container_name: postgres_workshop_bad
    volumes:
      - db_postgres_bad:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=workshop_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      postgres_workshop:
        condition: service_healthy
    ports:
      # No especificamos el puerto del host (ej. "8080:8080")
      # para que Docker asigne puertos aleatorios a cada réplica sin conflictos.
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_workshop:5432/workshop_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - vaadin.productionMode=true

volumes:
  db_postgres_bad: