# .github/workflows/ci.yml
name: Java CI with Maven

on:
  push:
    branches: [ "main", "parte-*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        # Ejecuta el build con el perfil de producción para asegurar que todo compile
        # correctamente. -DskipTests se usa aquí por simplicidad, pero en un
        # proyecto real, aquí ejecutarías tus pruebas de unidad e integración.
        run: mvn -B clean package -DskipTests -Pproduction
