name: Deploy to Railway

on:
  push:
    branches: [ "parte-4-cicd-github-actions" ]
  pull_request:
    branches: [ "parte-4-cicd-github-actions" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build project
        run: mvn clean package -DskipTests

      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Login to Railway
        run: railway login --token ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy to Railway
        run: railway up

    