name: Deploy to Railway

on:
  push:
    branches: [ "parte-4-cicd-github-actions" ]
  pull_request:
    branches: [ "parte-4-cicd-github-actions" ]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build project
        run: mvn clean package -DskipTests

      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      # El paso de 'login' se ha eliminado.

      - name: Deploy to Railway
        # Le pasamos el token como una variable de entorno al comando 'up'
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up